### ISSUE TITLE
Can you provide the Epinions dataset? Thx

### ISSUE THREAD

**Issue by dingqi** [alge24/DyGNN#4]
Thx for sharing the source code. Can you provide the Epinions dataset? After an extensive search on the Web, I cannot find the one you use in your paper (according to the statistics of the datasets.)

**Comment by alge24** [comment]
Please find the dataset at https://drive.google.com/file/d/1N54I-Gs6mS4YW_O6XfVLi1XMljQnIYEY/view?usp=sharing

**Comment by dingqi** [comment]
Thx a lot.
